name: Bersih

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'Cleaning'
        required: true
        default: 'Ok'

jobs:
  build:
    name: Beberes dulu gaes by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Display Inputs
      run: |

    - name: Clean-up
      uses: a02-trial/clean_actions@main

    - name: Cleanup Workspace
      if: always()
      run: |
        cd ${{ github.workspace }}
        rm -rf android-recovery
        df -h
